### ISSUE TITLE
Graph QL does not check the checkbox to select when sending a request

### ISSUE THREAD

**Issue by ryusei0709** [postmanlabs/raml1-to-postman#89]
- Postman v11.2.0
- OS: Mac M1

We are testing our API with Graph QL.

When I select Query and send a request to localhost, the checkbox is not checked when I click on the checkbox.

Is it just me or is this happening?

**Comment by VShingala** [comment]
Hey @ryusei0709, This repository only deals with importing RAML 1.0 definitions into Postman. Could you raise your issue over at https://github.com/postmanlabs/postman-app-support/issues with provided details? This will help the our team help you better.

**Comment by ryusei0709** [comment]
@VShingala 
Thank you very much.
